const actionTypes = {
	LOAD_CARDS: 'LOAD_CARDS',
	LOAD_RANDOM_CARDS: 'LOAD_RANDOM_CARDS',
	LOAD_CARD: 'LOAD_CARD',
	LOAD_DECKS: 'LOAD_DECKS',
	REMOVE_CARD: 'REMOVE_CARD',
	LOAD_LIST: 'LOAD_LIST',
	LOAD_COLLECTION: 'LOAD_COLLECTION',
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
	AUTH_SIGNOUT: 'AUTH_SIGNOUT',
	AUTH_SIGNOUT_ERROR: 'AUTH_SIGNOUT_ERROR'
};

export default actionTypes;
