const actionTypes = {
	LOAD_CARDS: 'LOAD_CARDS',
	LOAD_RANDOM_CARDS: 'LOAD_RANDOM_CARDS',
	LOAD_CARD: 'LOAD_CARD',
	LOAD_DECKS: 'LOAD_DECKS',
	LOAD_LIST: 'LOAD_LIST',
	LOAD_COLLECTION: 'LOAD_COLLECTION'
};

export default actionTypes;
